# Generated by Django 5.2.1 on 2025-06-09 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommendation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='music_list',
            name='link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
