# Generated by Django 5.2.1 on 2025-07-08 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommendation', '0002_music_list_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='music_list',
            name='genre',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
