# Generated by Django 5.2.1 on 2025-10-05 16:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("recommendation", "0003_music_list_genre"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="music_list",
            name="genre",
        ),
        migrations.RemoveField(
            model_name="music_list",
            name="nation",
        ),
    ]
